version: "3.8"
services:
    website:
        container_name: mesonmontesdetoledo_website
        hostname: mesonmontesdetoledo_website
        build: .
        ports: 
            - 3000:3000
        volumes:
            - .:/var/www/html/mesonmontesdetoledo_website
        command: tail -f /dev/null
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - mesonmontesdetoledo_web

networks:
    mesonmontesdetoledo_web:
        name: mesonmontesdetoledo_web
        driver: bridge
        external: true

volumes:
    persistent:
